### PR TITLE
Update Arch Linux repository

### PR DESCRIPTION
**Pull request by roland-5**
Replace this paragraph with a description of your changes and rationale.

Checklist:
- [ ] Did you update the CHANGELOG?
- [ ] If you introduced dependencies: Did you update the `mesonlsp.spec`, `scripts/create_license_file.sh` and *all* GitHub Actions files?
- [ ] Did you run a profiler, if you inserted a lot of C++ code, especially in the Lexer, Parser or the Type Analyzer?

Fixes #NNNN

### CODE REVIEW

**Comment by tristan957** [comment]
Does the package only exist for x86_64? How many other architectures is it available for? I only ask because the URL is architecture-specific.

**Comment by roland-5** [comment]
Arch Linux officially support only x86_64. There is ALARM (Arch Linux ARM) but this is not official Arch Linux project and I don't even see in theirs repos `mesonlsp` package.

**Comment by polyzen** [comment]
mesonlsp hasn't shown up on [their builder](https://archlinuxarm.org/builder/in-log/) yet, but I figure it will eventually.

**Comment by JCWasmx86** [comment]
I'm extremely happy that this is now an Arch Linux package, thank you so much for your work maintaining the AUR package @polyzen  and for this PR @roland-5.

**Pull request merged**
