### PR TITLE
Build universal binary (x86_64 and arm64) in CI

### PR DESCRIPTION
**Pull request by fwcd**
This would make the language server run natively on Apple Silicon Macs.

### CODE REVIEW

**Comment by JCWasmx86** [comment]
Thanks a lot for that, but I have several concerns with it.

- The binary can't be tested in CI on arm64
- I have no M1/M2 mac to debug any specific problems there.


Furthermore:
- ReleaseUpload.yml should be uploaded, too as it is the workflow providing the binaries for releases
- Please update the CHANGELOG.md file

**Comment by fwcd** [comment]
> - The binary can't be tested in CI on arm64
> - I have no M1/M2 mac to debug any specific problems there.

That's true, but as long it builds I would consider it better than nothing for now. Free Apple Silicon runners [will come at some point](https://github.com/actions/runner-images/issues/8439#issuecomment-1755601587), at which point CI could be updated to also run tests on arm64.

> ReleaseUpload.yml should be uploaded, too as it is the workflow providing the binaries for releases
> Please update the CHANGELOG.md file

Done

**Comment by JCWasmx86** [comment]
Thanks for addressing my concerns. Sadly CI is currently borked, give me a few hours to fix it

**Comment by fwcd** [comment]
Yes, the `sourcekit-lsp` commit has to be updated to the rebased commit (along with any changes that have to be migrated)

**Comment by JCWasmx86** [comment]
CI is now fixed on main

**Comment by JCWasmx86** [comment]
Thanks a lot!

**Comment by fwcd** [comment]
Note: You may have to update the artifact paths in CI, apparently SwiftPM places universal binaries under `.build/apple` (since it uses XCBuild when compiling universal binaries, see [this article](https://www.smileykeith.com/2020/12/24/swiftpm-cross-compile/)).

```diff
diff --git a/.github/workflows/Build.yml b/.github/workflows/Build.yml
index 939b7f0..76a73f8 100644
--- a/.github/workflows/Build.yml
+++ b/.github/workflows/Build.yml
@@ -61,7 +61,7 @@ jobs:
           ./scripts/run_wrap_tests.sh
           swift build -c release --arch x86_64 --arch arm64
           mkdir -p ${{ github.workspace }}/Artifacts
-          sudo cp .build/release/Swift-MesonLSP ${{ github.workspace }}/Artifacts/Swift-MesonLSP
+          sudo cp .build/apple/Products/Release/Swift-MesonLSP ${{ github.workspace }}/Artifacts/Swift-MesonLSP
       - uses: actions/upload-artifact@v3
         with:
           name: MacOS${{ matrix.version }}.zip
diff --git a/.github/workflows/ReleaseUpload.yml b/.github/workflows/ReleaseUpload.yml
index cb0ce4f..eee07eb 100644
--- a/.github/workflows/ReleaseUpload.yml
+++ b/.github/workflows/ReleaseUpload.yml
@@ -14,7 +14,7 @@ jobs:
         run: |
           swift build -c release --static-swift-stdlib
           ./scripts/create_license_bundle.sh
-          zip -9jpr Swift-MesonLSP.zip .build/release/Swift-MesonLSP 3rdparty.txt COPYING
+          zip -9jpr Swift-MesonLSP.zip .build/apple/Products/Release/Swift-MesonLSP 3rdparty.txt COPYING
       - name: Upload to release
         uses: xresloader/upload-to-github-release@main
         with:
```

**Comment by kgantchev** [comment]
> That's true, but as long it builds I would consider it better than nothing for now. Free Apple Silicon runners [will come at some point](https://github.com/actions/runner-images/issues/8439#issuecomment-1755601587), at which point CI could be updated to also run tests on arm64.


You can use the [FlyCI](https://www.flyci.net/)'s M1 and M2 runners. Our runners are on average 2x faster and 2x cheaper than GitHub's **AND** we have a free tier for OSS projects (see below).

## Install Instructrions 

Easily replace your M1 runners: 
```diff
jobs:
 ci:
-    runs-on: macos-latest
+    runs-on: flyci-macos-large-latest-m1
   steps:
   - name: 👀 Checkout repo
     uses: actions/checkout@v4
```

Or try the M2 runners: 
```diff
jobs:
  ci:
-    runs-on: macos-latest
+    runs-on: flyci-macos-large-latest-m2
    steps:
      - name: 👀 Checkout repo
        uses: actions/checkout@v4
 ```

## Pricing  

| Processor | vCPU | RAM (GB) | Storage | Label | Price on FlyCI | Price on GitHub |
|-----------|-------|-----------|----------|-------------------------------|----------------|-----------------|
| M1        | 4    | 7        | 28 GB | flyci-macos-large-latest-m1   | $0.06          | -             |
| M1        | 8    | 14       | 28 GB | flyci-macos-xlarge-latest-m1  | $0.12          | $0.16           |
| M2        | 4    | 7        | 28 GB | flyci-macos-large-latest-m2   | $0.08          | -             |
| M2        | 8    | 14       | 28 GB | flyci-macos-xlarge-latest-m2  | $0.16          | -             |

## 500 mins/month Free for Public Repos

If your repo is public, then FlyCI offers 500 mins/month of free M1 runner usage with the `flyci-macos-large-latest-m1` runner.  

Best Regards,
Kiril Gantchev
CEO and co-founder of [FlyCI](https://flyci.net)

**Comment by JCWasmx86** [comment]
Hey, thanks for reaching out! I'm sorry, but I won't accept any kind of unwanted advertising in my repos. It would have been more fitting if you had started a discussion in one of your repositories and tagged me. If that had been the case, it might have been somewhat more acceptable. However, polluting a (long-closed!) pull request with your product is inappropriate. I prefer to keep my repositories focused on their intended purpose.

**Comment by kgantchev** [comment]
> I'm sorry, but I won't accept any kind of unwanted advertising in my repos. It would have been more fitting if you had started a discussion in one of your repositories and tagged me. If that had been the case, it might have been somewhat more acceptable.  

I apologize if I'm intruding. I deleted my comment. I'm not too technical so I'm not sure what's the best etiquette to reach out to people on GitHub. Thanks for the helpful advice. Again, my apologies!

**Pull request merged**
